### ISSUE TITLE
Not escaping commands

### ISSUE THREAD

**Issue by jory** [abelsonlive/cl-meats#2]
Some individuals (trollish names withheld) were sending meatspace messages ala 

```
`rm -rf ~` 
```

Which apparently was being executed by meatspeak.

Not sure if the same issue applies to this code.

**Comment by chee** [comment]
the name is weedbro by the way

**Comment by abelsonlive** [comment]
Hey meats

I am so so so sorry for this. I was pretty sure I had quoted everything in this repo, but I did initially post a script late last night which was not secure.  I've now deleted those gists and updated `cl-meats` so that this won't happen again.

I wish I had a better excuse for this rather than carelessness or naivité, but I really don't.  The truth is I'm pretty new to open source web development - I mostly do statistical programming -  and I'm still learning the standards and etiquette.  So please accept my apology for jeopardizing the safety of the community.

That being said, if someone could take the time to explain to me exactly how this posed a security threat, i'd really appreciate the guidance.

**Comment by tarmstrong** [comment]
I didn't see the actual exploit in action, but generally, when you send user input to the command line, you have to be careful of a few things:
1. If you are placing the argument in quotes, people can write a meatspace message like "It's cold today" and it will break because "s cold today" happens outside the quotes. This won't break every command.
2. If the function you are using allows shell scripting syntax, people can do nasty stuff like add stuff in backticks:
   
   ```
   This is a meatspace message `rm -rf ~/`
   ```
   
   This runs the `rm -rf ~/` command before running the `say` command.

If you want to avoid this in the future, the safest thing to do is use the [subprocess](http://docs.python.org/2/library/subprocess.html) library, which was created to help users avoid this kind of problem.

I think this is the best way:

```
subprocess.call(['say', '-v', voice, '-r', str(rate), mesg])
```

(NB I am not an expert in this sort of thing but I hope this helps! Can anyone verify that this is good advice?)

**Comment by sneakyness** [comment]
"He huffed, and he puffed, and he blew my home directories down" -the big bad weedbro

Isn't virtualenvwrapper a thing? Probably a good idea here, subprocesses or not. <3

**Comment by justinabrahms** [comment]
This sounds likes sane advice, @tarmstrong. Strings to test with:

```
say a ' b " c
say test; and; again
say $(date)
say `date`
say null characters \0 are fun times
```

**Comment by abelsonlive** [comment]
so now everything is quoted and run as a subprocess, I'm gonna close this issue:

https://github.com/abelsonlive/cl-meats/commit/09efd294f526d47eb534589c818a5cbf5a1ccac2
